# Generated by Django 5.0.6 on 2024-06-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_customers_alter_product_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='iamge',
            new_name='image',
        ),
    ]
