# Generated by Django 5.1.3 on 2024-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_customers_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='vat_number',
            field=models.IntegerField(),
        ),
    ]
