# Generated by Django 5.1.3 on 2024-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_customers_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='blog.attribute'),
        ),
    ]
